### ISSUE TITLE
remove rnaspades version overwrite

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaT_Assembly#2]
Please remove this line
       String spades_container_prod = "bryce911/spades:3.15.4"

JGI is using 3.15.2 so we should use the same version. That is specified in https://code.jgi.doe.gov/BFoster/jgi_meta_wdl/raw/main1.0/metatranscriptome/metatranscriptome_assy_rnaspades.wdl we don't need to specify this.

**Comment by kaijli** [comment]
I want to be able to print the docker container into the info file, so i changed the spade container to match for now https://github.com/microbiomedata/metaT_Assembly/commit/8bcdd8ba02632c246c25e79db0f73e61a4fe599a
