### ISSUE TITLE
assembly info file doesn't get named by prefix. 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaT_Assembly#3]
I think you are missing an underscore here https://github.com/microbiomedata/metaT_Assembly/blob/556d07106175abcf25582bbbcd7e877ff04b263e/metaT_assembly.wdl#L204
the info file is being named metaT_assy.info instead of appending the prefix to the file name.

**Comment by kaijli** [comment]
fixed https://github.com/microbiomedata/metaT_Assembly/commit/645994e7ad01eeb58ebdef35ad415266f9c831bb
