### ISSUE TITLE
prefix should use colon not underscore for finishing step

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaT_Assembly#4]
The prefix variable passed to finish_asm should have a colon and not an underscore
https://github.com/microbiomedata/metaT_Assembly/blob/556d07106175abcf25582bbbcd7e877ff04b263e/metaT_assembly.wdl#L137

The general rule is that file names use `nmdc_` (this is a cromwell restriction) and headers use `nmdc:`

**Comment by kaijli** [comment]
All the prefixes should have [this substitution](https://github.com/microbiomedata/metaT_Assembly/blob/556d07106175abcf25582bbbcd7e877ff04b263e/metaT_assembly.wdl#L10) applied to them, but I'll go through and check everything.
`String prefix=sub(proj_id, ":", "_")`

**Comment by aclum** [comment]
Correct, that is the problem. That substitution should be for file names only. For the prefixes within a file, contig headers, it should use the colon. See some example data from production runs example:
```
/global/cfs/cdirs/m3408/results/nmdc:omprc-11-fmxcdq73/nmdc:wfmgas-11-had2wk78.1> head -1  nmdc_wfmgas-11-had2wk78.1_contigs.fna
>nmdc:wfmgas-11-had2wk78.1_scf_1_c1
```

**Comment by kaijli** [comment]
> The prefix variable passed to finish_asm should have a colon and not an underscore

Is this still applicable? the colon will break the finish_asm renaming. there's nothing in finish_asm that needs the colon version

**Comment by kaijli** [comment]
checked through everything to make sure finish_asm files had the right project id / prefixes https://github.com/microbiomedata/metaT_Assembly/commit/1518334743ba8cb9e61139794a3b22d198943c50

**Comment by aclum** [comment]
The way you have it now looks correct. The files are named with an '_'  (ie nmdc_wfmgan-12-gbysvd76.1_imgap.info) and the headers within the files have colons ':' (ie nmdc:wfmgan-12-gbysvd76.1_0000001)
